Repository bisq-network/bisq2, pull requests merged in 2024-06, with the labels that each got.

#2232 WhonixTorController: Implement TAKEOWNERSHIP command
  network/tor/tor/src/main/java/bisq/tor/controller/ControlCommandFailedException.java
  network/tor/tor/src/main/java/bisq/tor/controller/WhonixTorController.java
Labels: tor

#2237 Refactor `DontShowAgainService`
  apps/desktop/desktop-app/src/main/java/bisq/desktop_app/DesktopApplicationService.java
  apps/desktop/desktop/src/main/java/bisq/desktop/DesktopController.java
  apps/desktop/desktop/src/main/java/bisq/desktop/ServiceProvider.java
  apps/desktop/desktop/src/main/java/bisq/desktop/common/Browser.java
  apps/desktop/desktop/src/main/java/bisq/desktop/components/overlay/Overlay.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/offerbook/BisqEasyOfferbookController.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/offerbook/MarketChannelItem.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/open_trades/trade_state/TradeStateController.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/settings/preferences/PreferencesController.java
  apps/desktop/desktop/src/main/java/bisq/desktop/overlay/onboarding/welcome/WelcomeController.java
  i18n/src/main/resources/bisq_easy.properties
  settings/src/main/java/bisq/settings/DontShowAgainService.java
  settings/src/main/java/bisq/settings/FavouriteMarketsService.java
Labels: refactoring

#2242 Implement WhonixTorControlReader
  network/tor/tor/src/main/java/bisq/tor/controller/BootstrapEventParser.java
  network/tor/tor/src/main/java/bisq/tor/controller/WhonixTorControlReader.java
  network/tor/tor/src/main/java/bisq/tor/controller/WhonixTorController.java
Labels: tor

#2241 tor: Implement BootstrapEventParser
  network/tor/tor/src/main/java/bisq/tor/controller/BootstrapEventParser.java
Labels: tor

#2240 Remove option to hide messages in offerbook chat
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/offerbook/BisqEasyOfferbookController.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/offerbook/BisqEasyOfferbookModel.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/offerbook/BisqEasyOfferbookView.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/ChatMessageContainerController.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/ChatMessagesListController.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/settings/preferences/PreferencesController.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/settings/preferences/PreferencesModel.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/settings/preferences/PreferencesView.java
  chat/src/main/java/bisq/chat/notifications/ChatNotificationService.java
  i18n/src/main/resources/bisq_easy.properties
  i18n/src/main/resources/chat.properties
Labels: ui

#2269 TorControlProtocol: Merge MidReplyLine and DataReplyLine
  network/tor/tor/src/main/java/bisq/tor/controller/TorControlProtocol.java
Labels: tor

#2286 Add fixed Bisq 2 onion-grater profile
  network/network/src/main/java/bisq/network/p2p/node/transport/TorTransportService.java
  network/tor/tor/onion-grater/40_bisq.yml
  network/tor/tor/src/main/java/bisq/tor/TorService.java
  network/tor/tor/src/main/java/bisq/tor/controller/NativeTorController.java
  network/tor/tor/src/main/java/bisq/tor/controller/TorControlProtocol.java
  network/tor/tor/src/main/java/bisq/tor/controller/TorController.java
  network/tor/tor/src/main/java/bisq/tor/controller/WhonixTorControlReader.java
  network/tor/tor/src/main/java/bisq/tor/controller/exceptions/CannotConnectWithTorException.java
  network/tor/tor/src/main/java/bisq/tor/controller/exceptions/CannotSendCommandToTorException.java
  network/tor/tor/src/main/java/bisq/tor/onionservice/OnionServicePublishService.java
Labels: whonix

#2279 TorControlProtocol: Wrap IOException into CannotSendCommandToTorException
  network/tor/tor/src/main/java/bisq/tor/controller/TorControlProtocol.java
  network/tor/tor/src/main/java/bisq/tor/controller/TorController.java
  network/tor/tor/src/main/java/bisq/tor/controller/exceptions/CannotSendCommandToTorException.java
Labels: refactoring, tor

#2252 Update dropdown in chat messages
  apps/desktop/desktop/src/main/java/bisq/desktop/components/controls/BisqPopupMenu.java
  apps/desktop/desktop/src/main/java/bisq/desktop/components/controls/DropdownMenu.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/ChatMessagesListController.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/ChatMessagesListModel.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/message_box/BubbleMessageBox.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/message_box/PeerOfferMessageBox.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/message_box/PeerTextMessageBox.java
Labels: ui, refactoring

#2288 Fix Tor startup issues on Windows
  network/tor/tor/src/main/java/bisq/tor/controller/TorControlProtocol.java
Labels: tor

#2293 Add sidebar copy buttons to UserProfileSidebar
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/sidebar/UserProfileSidebar.java
Labels: ui

#2295 Improvements in user profile details
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/sidebar/UserProfileSidebar.java
Labels: ui

#2297 Update more options menu in peer message
  apps/desktop/desktop/src/main/java/bisq/desktop/components/controls/DropdownMenu.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/message_box/PeerTextMessageBox.java
Labels: ui

#2305 Implement new design for user profile sidebar
  apps/desktop/desktop/src/main/java/bisq/desktop/components/controls/MenuItem.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/sidebar/UserProfileSidebar.java
  apps/desktop/desktop/src/main/resources/css/chat.css
  apps/desktop/desktop/src/main/resources/css/controls.css
  apps/desktop/desktop/src/main/resources/css/images.css
  apps/desktop/desktop/src/main/resources/images/chat/ignore/ignore-green.png
  apps/desktop/desktop/src/main/resources/images/chat/ignore/ignore-green@2x.png
  apps/desktop/desktop/src/main/resources/images/chat/ignore/ignore-grey.png
  apps/desktop/desktop/src/main/resources/images/chat/ignore/ignore-grey@2x.png
  apps/desktop/desktop/src/main/resources/images/chat/ignore/ignore-white.png
  apps/desktop/desktop/src/main/resources/images/chat/ignore/ignore-white@2x.png
  apps/desktop/desktop/src/main/resources/images/chat/mention/mention-green.png
  apps/desktop/desktop/src/main/resources/images/chat/mention/mention-green@2x.png
  apps/desktop/desktop/src/main/resources/images/chat/mention/mention-grey.png
  apps/desktop/desktop/src/main/resources/images/chat/mention/mention-grey@2x.png
  apps/desktop/desktop/src/main/resources/images/chat/mention/mention-white.png
  apps/desktop/desktop/src/main/resources/images/chat/mention/mention-white@2x.png
  apps/desktop/desktop/src/main/resources/images/chat/private-chat/private-chat-green.png
  apps/desktop/desktop/src/main/resources/images/chat/private-chat/private-chat-green@2x.png
  apps/desktop/desktop/src/main/resources/images/chat/private-chat/private-chat-grey.png
  apps/desktop/desktop/src/main/resources/images/chat/private-chat/private-chat-grey@2x.png
  apps/desktop/desktop/src/main/resources/images/chat/private-chat/private-chat-white.png
  apps/desktop/desktop/src/main/resources/images/chat/private-chat/private-chat-white@2x.png
  apps/desktop/desktop/src/main/resources/images/chat/report/report-green.png
  apps/desktop/desktop/src/main/resources/images/chat/report/report-green@2x.png
  apps/desktop/desktop/src/main/resources/images/chat/report/report-grey.png
  apps/desktop/desktop/src/main/resources/images/chat/report/report-grey@2x.png
  apps/desktop/desktop/src/main/resources/images/chat/report/report-white.png
  apps/desktop/desktop/src/main/resources/images/chat/report/report-white@2x.png
  apps/desktop/desktop/src/main/resources/images/chat/undo-ignore/undo-ignore-green.png
  apps/desktop/desktop/src/main/resources/images/chat/undo-ignore/undo-ignore-green@2x.png
  apps/desktop/desktop/src/main/resources/images/chat/undo-ignore/undo-ignore-grey.png
  apps/desktop/desktop/src/main/resources/images/chat/undo-ignore/undo-ignore-grey@2x.png
  apps/desktop/desktop/src/main/resources/images/chat/undo-ignore/undo-ignore-white.png
  apps/desktop/desktop/src/main/resources/images/chat/undo-ignore/undo-ignore-white@2x.png
  i18n/src/main/resources/chat.properties
Labels: ui

#2312 Peer message and user porfile siderbar improvements
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/message_box/PeerTextMessageBox.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/sidebar/UserProfileSidebar.java
Labels: ui

#2330 packaging: Support Bisq 1 LICENSE file
  apps/desktop/desktop-app-launcher/build.gradle.kts
  apps/desktop/desktop-app-launcher/maintainer_public_keys/387C8307.asc
  apps/desktop/desktop-app-launcher/maintainer_public_keys/E222AA02.asc
  build-logic/packaging/src/main/kotlin/bisq/gradle/packaging/JPackageTask.kt
  build-logic/packaging/src/main/kotlin/bisq/gradle/packaging/MergeOsSpecificJarHashesTask.kt
  build-logic/packaging/src/main/kotlin/bisq/gradle/packaging/PackagingPlugin.kt
  build-logic/packaging/src/main/kotlin/bisq/gradle/packaging/PackagingPluginExtension.kt
  build-logic/packaging/src/main/kotlin/bisq/gradle/packaging/ReleaseBinariesTaskFactory.kt
  build-logic/packaging/src/main/kotlin/bisq/gradle/packaging/jpackage/JPackageAppConfig.kt
  build-logic/packaging/src/main/kotlin/bisq/gradle/packaging/jpackage/PackageFactory.kt
  build-logic/packaging/src/main/kotlin/bisq/gradle/packaging/jpackage/package_formats/LinuxPackages.kt
  build-logic/packaging/src/main/kotlin/bisq/gradle/packaging/jpackage/package_formats/MacPackage.kt
  build-logic/packaging/src/main/kotlin/bisq/gradle/packaging/jpackage/package_formats/WindowsPackage.kt
Labels: packaging

#2319 packaging: Rename jpackage output to GitHub binary names
  build-logic/packaging/src/main/kotlin/bisq/gradle/packaging/PackagingPlugin.kt
  build-logic/packaging/src/main/kotlin/bisq/gradle/packaging/ReleaseBinariesTaskFactory.kt
Labels: packaging

#2331 Fix launcher update jar name
  application/src/main/java/bisq/updater/UpdaterUtils.java
  apps/desktop/desktop-app/build.gradle.kts
Labels: bug

#2332 tor: Remove lock if not running
  network/tor/tor/src/main/java/bisq/tor/TorService.java
Labels: bug, tor

#2340 Add reactions to my text messages
  apps/desktop/desktop/src/main/java/bisq/desktop/components/controls/BisqMenuItem.java
  apps/desktop/desktop/src/main/java/bisq/desktop/components/controls/DrawerMenu.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/ChatMessageListItem.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/message_box/BubbleMessageBox.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/message_box/MyOfferMessageBox.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/message_box/MyTextMessageBox.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/message_box/PeerTextMessageBox.java
  apps/desktop/desktop/src/main/resources/css/controls.css
Labels: ui

#2339 Add license and state changes due to the use of the Noto Emoji project
  README.md
  apps/desktop/desktop/src/main/resources/images/chat/message-actions/react-menu/LICENSE.txt
  apps/desktop/desktop/src/main/resources/images/chat/reactions/LICENSE.txt
  apps/desktop/desktop/src/main/resources/images/image-assets.md
Labels: documentation
