Repository bisq-network/bisq2, pull requests merged in 2024-04, with the labels that each got.

#1971 Add version number to splash screen
  apps/desktop/desktop/src/main/java/bisq/desktop/splash/SplashController.java
  apps/desktop/desktop/src/main/java/bisq/desktop/splash/SplashModel.java
  apps/desktop/desktop/src/main/java/bisq/desktop/splash/SplashView.java
Labels: ui, improvement

#1976 Fix alignment issue in create offer wizard
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/trade_wizard/direction/TradeWizardDirectionView.java
Labels: bug, ui

#1977 Refactor chat message container
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/ChatMessageContainerController.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/ChatMessageContainerModel.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/ChatMessageContainerView.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/components/ChatMentionPopupMenu.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/components/CitationBlock.java
Labels: refactoring

#1980 Refactor message boxes
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/ChatMessageListCellFactory.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/message_box/MyOfferMessageBox.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/message_box/MyTextMessageBox.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/message_box/PeerOfferMessageBox.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/message_box/PeerTextMessageBox.java
Labels: refactoring

#1992 Add custom errorLabel to MaterialTextField (rebase of #1901)
  apps/desktop/desktop/src/main/java/bisq/desktop/components/controls/MaterialTextField.java
Labels: ui

#1993 Improve materialtextfield validation
  apps/desktop/desktop/src/main/java/bisq/desktop/components/controls/MaterialTextField.java
  apps/desktop/desktop/src/main/java/bisq/desktop/components/controls/validator/NumberValidator.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/authorized_role/security_manager/SecurityManagerView.java
  apps/desktop/desktop/src/main/resources/css/text.css
Labels: ui

#1998 Add more details if takers offer is not found in BisqEasyOfferbookChannel
  trade/src/main/java/bisq/trade/bisq_easy/protocol/messages/BisqEasyTakeOfferRequestHandler.java
Labels: improvement

#1994 Update number validation to be more strict
  apps/desktop/desktop/src/main/java/bisq/desktop/components/controls/validator/NumberValidator.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/settings/preferences/PreferencesView.java
Labels: bug, ui

#1916 Add custom style to take offer button
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/BisqEasyServiceUtil.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/offerbook/BisqEasyOfferbookUtil.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/trade_wizard/review/TradeWizardReviewController.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/ChatMessageListItem.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/message_box/MyOfferMessageBox.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/message_box/PeerOfferMessageBox.java
  apps/desktop/desktop/src/main/resources/css/chat.css
  apps/desktop/desktop/src/main/resources/css/controls.css
  i18n/src/main/resources/bisq_easy.properties
  i18n/src/main/resources/default.properties
Labels: ui, improvement

#2005 Unify markets table style in trade wizard
  apps/desktop/desktop/src/main/java/bisq/desktop/components/controls/SearchBox.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/trade_wizard/market/TradeWizardMarketView.java
  apps/desktop/desktop/src/main/resources/css/bisq_easy.css
Labels: ui

#2007 Add missing break in switch statement
  apps/desktop/desktop/src/main/java/bisq/desktop/components/cathash/CatHash.java
Labels: bug

#1999 Add price step when creating a Buy offer
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/BisqEasyServiceUtil.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/take_offer/TakeOfferController.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/take_offer/TakeOfferModel.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/take_offer/TakeOfferView.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/take_offer/price/TakeOfferPriceController.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/take_offer/price/TakeOfferPriceModel.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/take_offer/price/TakeOfferPriceView.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/take_offer/review/TakeOfferReviewController.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/trade_wizard/TradeWizardController.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/trade_wizard/TradeWizardView.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/trade_wizard/review/TradeWizardReviewController.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/trade_wizard/select_offer/TradeWizardSelectOfferView.java
  i18n/src/main/resources/bisq_easy.properties
  trade/src/main/java/bisq/trade/bisq_easy/protocol/messages/BisqEasyTakeOfferRequestHandler.java
Labels: ui

#2000 Fix encoding issue on Windows
  apps/desktop/desktop/src/main/java/bisq/desktop/components/controls/UnorderedList.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/take_offer/review/TakeOfferReviewView.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/trade_wizard/review/TradeWizardReviewController.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/trade_wizard/review/TradeWizardReviewView.java
  apps/desktop/desktop/src/main/java/bisq/desktop/overlay/chat_rules/ChatRulesView.java
Labels: bug, ui

#2009 Fix failing mailbox message delivery
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/ChatMessageListItem.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/ChatMessagesListController.java
  bonded-roles/src/main/java/bisq/bonded_roles/bonded_role/AuthorizedBondedRole.java
  bonded-roles/src/main/java/bisq/bonded_roles/oracle/AuthorizedOracleNode.java
  bonded-roles/src/main/java/bisq/bonded_roles/registration/BondedRoleRegistrationRequest.java
  chat/src/main/java/bisq/chat/bisqeasy/open_trades/BisqEasyOpenTradeMessage.java
  chat/src/main/java/bisq/chat/two_party/TwoPartyPrivateChatMessage.java
  network/network-common/src/main/java/bisq/network/common/Address.java
  network/network/src/main/java/bisq/network/p2p/node/Node.java
  network/network/src/main/java/bisq/network/p2p/node/transport/TorTransportService.java
  network/network/src/main/java/bisq/network/p2p/services/confidential/ConfidentialMessageService.java
  network/network/src/main/java/bisq/network/p2p/services/confidential/ack/AckMessage.java
  network/network/src/main/java/bisq/network/p2p/services/confidential/resend/ResendMessageService.java
  network/network/src/main/java/bisq/network/p2p/services/data/broadcast/Broadcaster.java
  network/network/src/main/java/bisq/network/p2p/services/data/storage/DataStorageService.java
  network/network/src/main/java/bisq/network/p2p/services/data/storage/MetaData.java
  network/network/src/main/java/bisq/network/p2p/services/data/storage/append/AppendOnlyDataStorageService.java
  network/network/src/main/java/bisq/network/p2p/services/data/storage/auth/AuthenticatedDataStorageService.java
  network/network/src/main/java/bisq/network/p2p/services/data/storage/mailbox/MailboxDataStorageService.java
  user/src/main/java/bisq/user/profile/UserProfile.java
  user/src/main/java/bisq/user/reputation/requests/AuthorizeAccountAgeRequest.java
  user/src/main/java/bisq/user/reputation/requests/AuthorizeSignedWitnessRequest.java
Labels: bug, network

#2013 Ignore check for meta data until end of May at remove.
  network/network/src/main/java/bisq/network/p2p/services/data/storage/DataStorageService.java
  network/network/src/main/java/bisq/network/p2p/services/data/storage/auth/AuthenticatedDataStorageService.java
Labels: network

#2015 Improve PeerGroupManager
  common/src/main/java/bisq/common/util/MemoryReport.java
  network/network/src/main/java/bisq/network/p2p/node/RequestResponseManager.java
  network/network/src/main/java/bisq/network/p2p/services/peer_group/PeerGroupManager.java
  network/network/src/main/java/bisq/network/p2p/services/peer_group/keep_alive/KeepAliveService.java
Labels: network

#2017 Add overlay to accept or reject new seller's price
  apps/desktop/desktop/src/main/java/bisq/desktop/components/controls/UnorderedList.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/BisqEasyServiceUtil.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/open_trades/trade_state/TradePhaseBox.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/open_trades/trade_state/TradeStateController.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/open_trades/trade_state/TradeStateModel.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/open_trades/trade_state/TradeStateView.java
  apps/desktop/desktop/src/main/resources/css/bisq_easy.css
  i18n/src/main/resources/bisq_easy.properties
  trade/src/main/java/bisq/trade/bisq_easy/protocol/messages/BisqEasyTakeOfferRequestHandler.java
Labels: feature, ui

#2022 Change reputation service to use a predefined 5-star system
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/offerbook/BisqEasyOfferbookUtil.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/trade_wizard/select_offer/TradeWizardSelectOfferView.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/ChatMessageListItem.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/components/ReputationScoreDisplay.java
  apps/desktop/desktop/src/main/resources/css/images.css
  apps/desktop/desktop/src/main/resources/images/icons/stars/star-green-hollow.png
  apps/desktop/desktop/src/main/resources/images/icons/stars/star-green-hollow@2x.png
  apps/desktop/desktop/src/main/resources/images/icons/stars/star-green.png
  apps/desktop/desktop/src/main/resources/images/icons/stars/star-green@2x.png
  apps/desktop/desktop/src/main/resources/images/icons/stars/star-grey-hollow.png
  apps/desktop/desktop/src/main/resources/images/icons/stars/star-grey-hollow@2x.png
  apps/desktop/desktop/src/main/resources/images/icons/stars/star-grey.png
  apps/desktop/desktop/src/main/resources/images/icons/stars/star-grey@2x.png
  apps/desktop/desktop/src/main/resources/images/icons/stars/star-half-green.png
  apps/desktop/desktop/src/main/resources/images/icons/stars/star-half-green@2x.png
  apps/desktop/desktop/src/main/resources/images/icons/stars/star-half-hollow-green.png
  apps/desktop/desktop/src/main/resources/images/icons/stars/star-half-hollow-green@2x.png
  apps/desktop/desktop/src/main/resources/images/icons/stars/star-half-hollow-white.png
  apps/desktop/desktop/src/main/resources/images/icons/stars/star-half-hollow-white@2x.png
  apps/desktop/desktop/src/main/resources/images/icons/stars/star-half-white.png
  apps/desktop/desktop/src/main/resources/images/icons/stars/star-half-white@2x.png
  apps/desktop/desktop/src/main/resources/images/icons/stars/star-white-hollow.png
  apps/desktop/desktop/src/main/resources/images/icons/stars/star-white-hollow@2x.png
  apps/desktop/desktop/src/main/resources/images/icons/stars/star-white.png
  apps/desktop/desktop/src/main/resources/images/icons/stars/star-white@2x.png
  apps/desktop/desktop/src/main/resources/images/icons/stars/star-yellow-hollow.png
  apps/desktop/desktop/src/main/resources/images/icons/stars/star-yellow-hollow@2x.png
  apps/desktop/desktop/src/main/resources/images/icons/stars/star-yellow.png
  apps/desktop/desktop/src/main/resources/images/icons/stars/star-yellow@2x.png
  user/src/main/java/bisq/user/reputation/ReputationScore.java
  user/src/main/java/bisq/user/reputation/ReputationService.java
  user/src/test/java/bisq/user/reputation/ReputationServiceTest.java
Labels: ui, improvement

#2026 Refactor: Use upper limit to return number of stars
  user/src/main/java/bisq/user/reputation/ReputationService.java
  user/src/test/java/bisq/user/reputation/ReputationServiceTest.java
Labels: refactoring

#2027 Refactor and fix bugs in peer exchange service
  network/network/src/integrationTest/java/bisq/network/p2p/AllNetworksIntegrationTest.java
  network/network/src/integrationTest/java/bisq/network/p2p/BaseNetworkTest.java
  network/network/src/integrationTest/java/bisq/network/p2p/BaseTest.java
  network/network/src/integrationTest/java/bisq/network/p2p/ClearNetIntegrationTest.java
  network/network/src/integrationTest/java/bisq/network/p2p/I2pIntegrationTest.java
  network/network/src/integrationTest/java/bisq/network/p2p/MockMessage.java
  network/network/src/integrationTest/java/bisq/network/p2p/TestProtobufAny.java
  network/network/src/integrationTest/java/bisq/network/p2p/TorIntegrationTest.java
  network/network/src/integrationTest/java/bisq/network/p2p/node/BaseNodesByIdTest.java
  network/network/src/integrationTest/java/bisq/network/p2p/node/ClearNetNodesByIdIntegrationTest.java
  network/network/src/integrationTest/java/bisq/network/p2p/node/I2PNodesByIdIntegrationTest.java
  network/network/src/integrationTest/java/bisq/network/p2p/node/TorNodesByIdIntegrationTest.java
  network/network/src/integrationTest/java/bisq/network/p2p/services/peer_group/PeerExchangeBase.java
  network/network/src/integrationTest/java/bisq/network/p2p/services/peer_group/PeerExchangeIntegrationTest.java
  network/network/src/integrationTest/java/bisq/network/p2p/services/peer_group/exchange/BasePeerExchangeServiceTest.java
  network/network/src/integrationTest/java/bisq/network/p2p/services/peer_group/exchange/ClearNetPeerExchangeServiceTest.java
  network/network/src/main/java/bisq/network/p2p/services/peer_group/PeerGroupManager.java
  network/network/src/main/java/bisq/network/p2p/services/peer_group/exchange/PeerExchangeService.java
  network/network/src/main/java/bisq/network/p2p/services/peer_group/exchange/PeerExchangeStrategy.java
Labels: bug, network, refactoring

#2028 Revert changes of meta data
  bonded-roles/src/main/java/bisq/bonded_roles/bonded_role/AuthorizedBondedRole.java
  bonded-roles/src/main/java/bisq/bonded_roles/oracle/AuthorizedOracleNode.java
  bonded-roles/src/main/java/bisq/bonded_roles/registration/BondedRoleRegistrationRequest.java
  chat/src/main/java/bisq/chat/bisqeasy/open_trades/BisqEasyOpenTradeMessage.java
  chat/src/main/java/bisq/chat/two_party/TwoPartyPrivateChatMessage.java
  network/network/src/main/java/bisq/network/p2p/services/confidential/ack/AckMessage.java
  network/network/src/main/java/bisq/network/p2p/services/data/storage/MetaData.java
  network/network/src/main/java/bisq/network/p2p/services/data/storage/auth/AuthenticatedDataStorageService.java
  user/src/main/java/bisq/user/profile/UserProfile.java
  user/src/main/java/bisq/user/reputation/requests/AuthorizeAccountAgeRequest.java
  user/src/main/java/bisq/user/reputation/requests/AuthorizeSignedWitnessRequest.java
Labels: network

#2029 Revert "Change PRIORITY in MetaData"
  bonded-roles/src/main/java/bisq/bonded_roles/release/ReleaseNotification.java
  bonded-roles/src/main/java/bisq/bonded_roles/security_manager/alert/AuthorizedAlertData.java
  bonded-roles/src/main/java/bisq/bonded_roles/security_manager/difficulty_adjustment/AuthorizedDifficultyAdjustmentData.java
  bonded-roles/src/main/java/bisq/bonded_roles/security_manager/min_reputation_score/AuthorizedMinRequiredReputationScoreData.java
  user/src/main/java/bisq/user/banned/BannedUserProfileData.java
  user/src/main/java/bisq/user/reputation/data/AuthorizedAccountAgeData.java
Labels: network

#2032 Add feedback for buyer in price step
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/trade_wizard/TradeWizardController.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/trade_wizard/price/TradeWizardPriceController.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/trade_wizard/price/TradeWizardPriceModel.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/trade_wizard/price/TradeWizardPriceView.java
  apps/desktop/desktop/src/main/resources/css/bisq_easy.css
  i18n/src/main/resources/bisq_easy.properties
Labels: feature, ui

#2037 Add DefaultNumberFormatter
  presentation/src/main/java/bisq/presentation/formatters/DefaultNumberFormatter.java
  presentation/src/test/java/bisq/presentation/formatters/DefaultNumberFormatterTest.java
Labels: ui

#2039 Fix performance bug at reputation view
  apps/desktop/desktop/src/main/java/bisq/desktop/common/converters/Converters.java
  apps/desktop/desktop/src/main/java/bisq/desktop/common/converters/DoubleStringConverter.java
  apps/desktop/desktop/src/main/java/bisq/desktop/common/converters/LongStringConverter.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/settings/preferences/PreferencesController.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/user/reputation/list/ReputationListController.java
  bonded-roles/src/main/java/bisq/bonded_roles/bonded_role/AuthorizedBondedRolesService.java
  network/network/src/main/java/bisq/network/http/ClearNetHttpClient.java
  network/network/src/main/java/bisq/network/p2p/services/peer_group/exchange/PeerExchangeService.java
  settings/src/main/java/bisq/settings/Cookie.java
  user/src/main/java/bisq/user/profile/UserProfileService.java
  user/src/main/java/bisq/user/profile/UserProfileStore.java
  user/src/main/java/bisq/user/reputation/SourceReputationService.java
Labels: ui

#2042 Refine Bisq Easy offer message
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/BisqEasyServiceUtil.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/offerbook/BisqEasyOfferbookUtil.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/trade_wizard/review/TradeWizardReviewController.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/ChatMessageListItem.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/message_box/BubbleMessageBox.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/message_box/MyOfferMessageBox.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/message_box/PeerOfferMessageBox.java
  apps/desktop/desktop/src/main/resources/css/chat.css
  apps/desktop/desktop/src/main/resources/css/text.css
  chat/src/main/java/bisq/chat/notifications/ChatNotificationService.java
  i18n/src/main/resources/bisq_easy.properties
Labels: ui, improvement

#2047 ControlPortFileParser: Handle "\r\n" newline encoding
  network/tor/tor/src/main/java/bisq/tor/process/ControlPortFileParser.java
Labels: bug, tor

#2048 Move TorInstallationFiles into TorInstaller
  network/tor/tor/src/integrationTest/java/bisq/tor/InstallerAndRunRaceConditionTest.java
  network/tor/tor/src/main/java/bisq/tor/TorService.java
  network/tor/tor/src/main/java/bisq/tor/installer/TorInstaller.java
Labels: refactoring, tor

#2052 Various fixes and improvements for buyer as maker case
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/open_trades/trade_state/TradeStateController.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/open_trades/trade_state/TradeStateView.java
  apps/desktop/desktop/src/main/resources/css/bisq_easy.css
  i18n/src/main/resources/bisq_easy.properties
Labels: bug, ui

#2053 Fixes in trade wizard's price step
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/trade_wizard/price/TradeWizardPriceController.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/trade_wizard/price/TradeWizardPriceView.java
Labels: bug, ui

#2062 TorService: Use AtomicBoolean compareAndSet
  network/tor/tor/src/main/java/bisq/tor/TorService.java
Labels: bug, tor

#2063 Fix Tor start-up deadlock
  network/tor/tor-common/src/main/java/bisq/network/tor/common/torrc/BaseTorrcGenerator.java
  network/tor/tor-local-network/src/main/java/bisq/tor/local_network/torrc/TestNetworkTorrcGeneratorFactory.java
  network/tor/tor-local-network/src/test/java/bisq/tor/local_network/DirectoryAuthorityTorrcGeneratorTests.java
  network/tor/tor-local-network/src/test/java/bisq/tor/local_network/InputStreamWaiterTests.java
  network/tor/tor-local-network/src/test/java/bisq/tor/local_network/RelayTorrcGeneratorTests.java
  network/tor/tor/src/main/java/bisq/tor/TorService.java
  network/tor/tor/src/main/java/bisq/tor/TorrcClientConfigFactory.java
  network/tor/tor/src/main/java/bisq/tor/process/ControlPortFilePoller.java
  network/tor/tor/src/main/java/bisq/tor/process/NativeTorProcess.java
  network/tor/tor/src/main/java/bisq/tor/process/TorStartupFailedException.java
Labels: bug, tor

#2066 Remove legacy Tor startup code
  common/src/integrationTest/java/bisq/common/io_watcher/DirectoryWatcherTests.java
  common/src/main/java/bisq/common/io_watcher/CouldNotInitializeDirectoryWatcherException.java
  common/src/main/java/bisq/common/io_watcher/DirectoryEventPublisher.java
  common/src/main/java/bisq/common/io_watcher/DirectoryEventSubscriber.java
  common/src/main/java/bisq/common/io_watcher/DirectoryEventSubscription.java
  common/src/main/java/bisq/common/io_watcher/DirectoryWatcher.java
  common/src/main/java/bisq/common/io_watcher/NoDirectoryChangesTimeoutException.java
  network/tor/tor/src/main/java/bisq/tor/TorService.java
  network/tor/tor/src/main/java/bisq/tor/process/ControlPortReadyWaiter.java
  network/tor/tor/src/main/java/bisq/tor/process/NativeTorProcess.java
Labels: refactoring, tor

#2067 Compute Tor bootstrap timeout from last event
  network/tor/tor/src/main/java/bisq/tor/controller/NativeTorController.java
  network/tor/tor/src/main/java/bisq/tor/controller/events/events/BootstrapEvent.java
Labels: bug, tor

#2122 Get SOCKS5 port from Tor daemon
  network/tor/tor/src/main/java/bisq/tor/TorService.java
  network/tor/tor/src/main/java/bisq/tor/controller/NativeTorController.java
Labels: improvement, tor

#2124 Move Tor ControlPortFile classes to control_port package
  network/tor/tor/src/main/java/bisq/tor/TorService.java
  network/tor/tor/src/main/java/bisq/tor/process/control_port/ControlPortFileParseFailureException.java
  network/tor/tor/src/main/java/bisq/tor/process/control_port/ControlPortFileParser.java
  network/tor/tor/src/main/java/bisq/tor/process/control_port/ControlPortFilePoller.java
Labels: refactoring, tor

#2126 Use system libraries when using system Tor
  network/tor/tor/src/main/java/bisq/tor/TorService.java
  network/tor/tor/src/main/java/bisq/tor/process/NativeTorProcess.java
Labels: improvement, tor

#2125 Prefer installed Tor package
  network/tor/tor/src/main/java/bisq/tor/TorService.java
  network/tor/tor/src/main/java/bisq/tor/process/NativeTorProcess.java
Labels: improvement, tor

#2128 Add offer list in Bisq Easy offerbook
  apps/desktop/desktop/src/main/java/bisq/desktop/components/controls/DropdownMenu.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/offerbook/BisqEasyOfferbookController.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/offerbook/BisqEasyOfferbookModel.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/offerbook/BisqEasyOfferbookUtil.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/offerbook/BisqEasyOfferbookView.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/offerbook/OfferMessageItem.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/ChatMessageContainerController.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/ChatMessageListItem.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/ChatMessagesListController.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/ChatMessagesListView.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/message_box/BubbleMessageBox.java
  apps/desktop/desktop/src/main/resources/css/base.css
  apps/desktop/desktop/src/main/resources/css/bisq_easy.css
  apps/desktop/desktop/src/main/resources/css/chat.css
  chat/src/main/java/bisq/chat/bisqeasy/offerbook/BisqEasyOfferbookMessage.java
  i18n/src/main/resources/bisq_easy.properties
  offer/src/main/java/bisq/offer/price/PriceUtil.java
  presentation/src/main/java/bisq/presentation/formatters/PercentageFormatter.java
Labels: feature, ui

#2133 Make Markets and Offer List columns collapsible
  apps/desktop/desktop/src/main/java/bisq/desktop/common/Transitions.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/offerbook/BisqEasyOfferbookController.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/offerbook/BisqEasyOfferbookModel.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/offerbook/BisqEasyOfferbookView.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/ChatMessageListItem.java
  apps/desktop/desktop/src/main/resources/css/bisq_easy.css
  apps/desktop/desktop/src/main/resources/css/images.css
  apps/desktop/desktop/src/main/resources/images/icons/list-view/list-view-green.png
  apps/desktop/desktop/src/main/resources/images/icons/list-view/list-view-green@2x.png
  apps/desktop/desktop/src/main/resources/images/icons/list-view/list-view-grey.png
  apps/desktop/desktop/src/main/resources/images/icons/list-view/list-view-grey@2x.png
  apps/desktop/desktop/src/main/resources/images/icons/list-view/list-view-white.png
  apps/desktop/desktop/src/main/resources/images/icons/list-view/list-view-white@2x.png
  apps/desktop/desktop/src/main/resources/images/icons/market/market-green.png
  apps/desktop/desktop/src/main/resources/images/icons/market/market-green@2x.png
  apps/desktop/desktop/src/main/resources/images/icons/market/market-grey.png
  apps/desktop/desktop/src/main/resources/images/icons/market/market-grey@2x.png
  apps/desktop/desktop/src/main/resources/images/icons/market/market-white.png
  apps/desktop/desktop/src/main/resources/images/icons/market/market-white@2x.png
  i18n/src/main/resources/bisq_easy.properties
Labels: ui, improvement
