Repository bisq-network/bisq2, pull requests merged in 2024-07, with the labels that each got.

#2366 Always show failed delivery status
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/ChatMessageListItem.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/message_box/BubbleMessageBox.java
Labels: ui

#2370 Add marker to indicate added reactions in react menu
  apps/desktop/desktop/src/main/java/bisq/desktop/components/controls/DrawerMenu.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/ChatMessageListItem.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/message_box/BubbleMessageBox.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/message_box/MyTextMessageBox.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/message_box/PeerTextMessageBox.java
  apps/desktop/desktop/src/main/resources/css/chat.css
  apps/desktop/desktop/src/main/resources/css/controls.css
Labels: ui

#2373 Show mailbox delivery status
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/ChatMessageListItem.java
  apps/desktop/desktop/src/main/resources/css/images.css
  apps/desktop/desktop/src/main/resources/images/chat/message-status/mailbox-green.png
  apps/desktop/desktop/src/main/resources/images/chat/message-status/mailbox-green@2x.png
  apps/desktop/desktop/src/main/resources/images/chat/message-status/mailbox-grey.png
  apps/desktop/desktop/src/main/resources/images/chat/message-status/mailbox-grey@2x.png
  apps/desktop/desktop/src/main/resources/images/chat/message-status/mailbox-white.png
  apps/desktop/desktop/src/main/resources/images/chat/message-status/mailbox-white@2x.png
Labels: ui

#2376 Improve handling of unprocessed reactions
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/message_box/BubbleMessageBox.java
  apps/desktop/desktop/src/main/resources/css/chat.css
  apps/desktop/desktop/src/main/resources/css/controls.css
  chat/src/main/java/bisq/chat/priv/PrivateChatChannelService.java
  chat/src/main/java/bisq/chat/two_party/TwoPartyPrivateChatChannelService.java
Labels: improvement

#2375 Improve UI styles in react menu
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/message_box/BubbleMessageBox.java
  apps/desktop/desktop/src/main/resources/css/chat.css
  apps/desktop/desktop/src/main/resources/css/controls.css
Labels: ui

#2378 Allow removing reactions in two party chat messages
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/ChatMessageListItem.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/ChatMessagesListController.java
  chat/src/main/java/bisq/chat/ChatChannelService.java
  chat/src/main/java/bisq/chat/ChatMessage.java
  chat/src/main/java/bisq/chat/bisqeasy/open_trades/BisqEasyOpenTradeMessage.java
  chat/src/main/java/bisq/chat/priv/PrivateChatChannelService.java
  chat/src/main/java/bisq/chat/priv/PrivateChatMessage.java
  chat/src/main/java/bisq/chat/pub/PublicChatMessage.java
  chat/src/main/java/bisq/chat/reactions/ChatMessageReaction.java
  chat/src/main/java/bisq/chat/reactions/PrivateChatMessageReaction.java
  chat/src/main/java/bisq/chat/reactions/TwoPartyPrivateChatMessageReaction.java
  chat/src/main/java/bisq/chat/two_party/TwoPartyPrivateChatChannelService.java
  chat/src/main/java/bisq/chat/two_party/TwoPartyPrivateChatMessage.java
  chat/src/main/proto/chat.proto
Labels: improvement

#2393 Clean up chat message class definition
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/authorized_role/mediator/MediatorModel.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/offerbook/BisqEasyOfferbookController.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/open_trades/BisqEasyOpenTradesController.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/open_trades/MyProtocolLogMessageBox.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/open_trades/PeerProtocolLogMessageBox.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/BaseChatController.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/BaseChatModel.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/common/CommonChatTabController.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/ChatMessageContainerController.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/ChatMessageContainerModel.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/ChatMessageListCellFactory.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/ChatMessageListItem.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/ChatMessagesListController.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/ChatMessagesListModel.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/ChatMessagesListView.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/message_box/BubbleMessageBox.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/message_box/LeaveChatMessageBox.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/message_box/MyOfferMessageBox.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/message_box/MyTextMessageBox.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/message_box/PeerOfferMessageBox.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/message_box/PeerTextMessageBox.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/priv/PrivateChatsController.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/sidebar/ChannelSidebar.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/sidebar/NotificationsSidebar.java
  chat/src/main/java/bisq/chat/ChatChannel.java
  chat/src/main/java/bisq/chat/ChatChannelSelectionService.java
  chat/src/main/java/bisq/chat/ChatChannelService.java
  chat/src/main/java/bisq/chat/ChatMessage.java
  chat/src/main/java/bisq/chat/bisqeasy/offerbook/BisqEasyOfferbookSelectionService.java
  chat/src/main/java/bisq/chat/bisqeasy/open_trades/BisqEasyOpenTradeSelectionService.java
  chat/src/main/java/bisq/chat/bisqeasy/private_chats/BisqEasyPrivateChatChannelSelectionService.java
  chat/src/main/java/bisq/chat/common/CommonChannelSelectionService.java
  chat/src/main/java/bisq/chat/notifications/ChatNotification.java
  chat/src/main/java/bisq/chat/notifications/ChatNotificationService.java
  chat/src/main/java/bisq/chat/priv/PrivateChatChannel.java
  chat/src/main/java/bisq/chat/priv/PrivateChatChannelService.java
  chat/src/main/java/bisq/chat/priv/PrivateChatMessage.java
  chat/src/main/java/bisq/chat/priv/PrivateGroupChatChannel.java
  chat/src/main/java/bisq/chat/pub/PublicChatChannelService.java
  chat/src/main/java/bisq/chat/pub/PublicChatMessage.java
Labels: refactoring

#2404 Improve chat messages' active reactions display
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/ChatMessageListItem.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/ReactionItem.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/message_box/BubbleMessageBox.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/message_box/MyTextMessageBox.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/message_box/PeerTextMessageBox.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/reactions_box/ActiveReactionsDisplayBox.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/reactions_box/ToggleReaction.java
  apps/desktop/desktop/src/main/resources/css/chat.css
Labels: ui

#2408 Always show message delivery states
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/ChatMessageListItem.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/message_box/BubbleMessageBox.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/message_box/MyOfferMessageBox.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/message_box/MyTextMessageBox.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/message_box/PeerTextMessageBox.java
Labels: ui

#2444 Merge fiat and btc payment methods in one step in trade wizard
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/trade_wizard/TradeWizardController.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/trade_wizard/TradeWizardView.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/trade_wizard/btc_payment_method/TradeWizardBitcoinPaymentMethodController.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/trade_wizard/btc_payment_method/TradeWizardBitcoinPaymentMethodModel.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/trade_wizard/btc_payment_method/TradeWizardBitcoinPaymentMethodView.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/trade_wizard/payment_methods/TradeWizardPaymentMethodsController.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/trade_wizard/payment_methods/TradeWizardPaymentMethodsModel.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/trade_wizard/payment_methods/TradeWizardPaymentMethodsView.java
  bisq-easy/src/main/java/bisq/bisq_easy/NavigationTarget.java
  i18n/src/main/resources/bisq_easy.properties
Labels: ui

#2459 PpgPublicKeyParser: Warn about uncertified subkeys
  build-logic/gradle-tasks/src/main/kotlin/bisq/gradle/tasks/signature/PpgPublicKeyParser.kt
Labels: build-system, wallet

#2460 build-logic: Support m out of n signature verification
  build-logic/gradle-tasks/src/main/kotlin/bisq/gradle/tasks/signature/SignatureVerifier.kt
Labels: build-system, wallet

#2466 Create independent buttons to delete message and an offer
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/message_box/BubbleMessageBox.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/message_box/MyOfferMessageBox.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/chat/message_container/list/message_box/MyTextMessageBox.java
Labels: bug, ui

#2501 Fix horizontal scroll issue in My Open Trades page
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/open_trades/BisqEasyOpenTradesView.java
Labels: bug

#2525 Improve payment methods page in take offer
  apps/desktop/desktop/src/main/java/bisq/desktop/common/utils/GridPaneUtil.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/take_offer/TakeOfferController.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/take_offer/payment_methods/TakeOfferPaymentController.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/take_offer/payment_methods/TakeOfferPaymentModel.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/take_offer/payment_methods/TakeOfferPaymentView.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/trade_wizard/payment_methods/AddCustomPaymentMethodBox.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/trade_wizard/payment_methods/TradeWizardPaymentMethodsController.java
  apps/desktop/desktop/src/main/java/bisq/desktop/main/content/bisq_easy/trade_wizard/payment_methods/TradeWizardPaymentMethodsView.java
  apps/desktop/desktop/src/main/resources/css/images.css
  apps/desktop/desktop/src/main/resources/images/payment/ach-.png
  apps/desktop/desktop/src/main/resources/images/payment/ach-@2x.png
  apps/desktop/desktop/src/main/resources/images/payment/amazon-.png
  apps/desktop/desktop/src/main/resources/images/payment/amazon-@2x.png
  apps/desktop/desktop/src/main/resources/images/payment/bizum-.png
  apps/desktop/desktop/src/main/resources/images/payment/bizum-@2x.png
  apps/desktop/desktop/src/main/resources/images/payment/cashapp-.png
  apps/desktop/desktop/src/main/resources/images/payment/cashapp-@2x.png
  apps/desktop/desktop/src/main/resources/images/payment/f2f-.png
  apps/desktop/desktop/src/main/resources/images/payment/f2f-@2x.png
  apps/desktop/desktop/src/main/resources/images/payment/pix-.png
  apps/desktop/desktop/src/main/resources/images/payment/pix-@2x.png
  apps/desktop/desktop/src/main/resources/images/payment/revolut-.png
  apps/desktop/desktop/src/main/resources/images/payment/revolut-@2x.png
  apps/desktop/desktop/src/main/resources/images/payment/sepa-.png
  apps/desktop/desktop/src/main/resources/images/payment/sepa-@2x.png
  apps/desktop/desktop/src/main/resources/images/payment/strike-.png
  apps/desktop/desktop/src/main/resources/images/payment/strike-@2x.png
  apps/desktop/desktop/src/main/resources/images/payment/upi-.png
  apps/desktop/desktop/src/main/resources/images/payment/upi-@2x.png
  apps/desktop/desktop/src/main/resources/images/payment/wise-.png
  apps/desktop/desktop/src/main/resources/images/payment/wise-@2x.png
  apps/desktop/desktop/src/main/resources/images/payment/zelle-.png
  apps/desktop/desktop/src/main/resources/images/payment/zelle-@2x.png
  i18n/src/main/resources/bisq_easy.properties
Labels: ui
